pre-commit hook: apply shellcheck suggestions

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,15 +1,8 @@
 #!/usr/bin/env bash
-export GIT_DIR=$(git rev-parse --git-common-dir)
+export GIT_DIR
+GIT_DIR=$(git rev-parse --git-common-dir)
 
 set -e
-
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
 
 exec 1>&2
 
@@ -24,32 +17,33 @@ exec 1>&2
 # running pre-commit, we can be sure that the commit is fine if we
 # get here *and* there are no changes.
 if git diff --staged --quiet; then
-	exit 0
+  exit 0
 fi
 
 # Note: exiting early here means that the commit hook doesn't fail
 # with git commit --amend when there are no changes
 
 # Fix whitespace (index [= cached/staged area])
+mapfile -t no_whitespace_glob < "$GIT_DIR/info/no-whitespace-files"
 tmpdiff=$(mktemp)
-trap "rm -f $tmpdiff" EXIT
-git diff --cached --no-color -- $(cat $GIT_DIR/info/no-whitespace-files) > $tmpdiff
-if [ -s $tmpdiff ]; then # if the patch is empty, git apply fails
-  git apply --cached -R $tmpdiff
-  git apply --cached --whitespace=fix $tmpdiff 2>&1 | sed -e '/trailing whitespace.$/ { N; d }' -re '/warning: [[:digit:]]+ lines? applied after fixing whitespace errors./d'
+trap 'rm -f "$tmpdiff"' EXIT
+git diff --no-textconv --binary --cached --no-color -- "${no_whitespace_glob[@]}" > "$tmpdiff"
+if [ -s "$tmpdiff" ]; then # if the patch is empty, git apply fails
+  git apply --cached -R "$tmpdiff"
+  git apply --cached --whitespace=fix "$tmpdiff" 2>&1 | sed -e '/trailing whitespace.$/ { N; d }' -re '/warning: [[:digit:]]+ lines? applied after fixing whitespace errors./d'
 fi
-rm -f $tmpdiff
+rm -f "$tmpdiff"
 trap - EXIT
 
 # Fix whitespace (working directory)
 tmpdiff=$(mktemp)
-trap "rm -f $tmpdiff" EXIT
-git diff --no-color -- $(cat $GIT_DIR/info/no-whitespace-files) > $tmpdiff
-if [ -s $tmpdiff ]; then # if the patch is empty, git apply fails
-  git apply -R $tmpdiff
+trap 'rm -f "$tmpdiff"' EXIT
+git diff --no-textconv --binary --no-color -- "${no_whitespace_glob[@]}" > "$tmpdiff"
+if [ -s "$tmpdiff" ]; then # if the patch is empty, git apply fails
+  git apply -R "$tmpdiff"
   git apply --whitespace=fix $tmpdiff 2>&1 | sed -e '/trailing whitespace.$/ { N; d }' -re '/warning: [[:digit:]]+ lines? applied after fixing whitespace errors./d'
 fi
-rm -f $tmpdiff
+rm -f "$tmpdiff"
 trap - EXIT
 
 # Check that there are any changes left after whitespace fixing
